project:
  type: website
  output-dir: docs

website:
  title: "Quantile World"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - unifpareto.qmd
      - logistic.qmd
      - burr.qmd
      - about.qmd

format:
  html:
    theme: vapor
    toc: true



